package hackwa.project.hackwacalendar;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;

/**
 * Created by core on 16/12/18.
 */

@Entity(tableName = "event_table")
public class Event {

    // autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    private int id;

    @NonNull
    @ColumnInfo(name = "event")
    private String mEvent;

    private int color;

    @NonNull
    private long timeInMillis;


    public Event(int color, @NonNull long timeInMillis, @NonNull String event) {
        this.mEvent = event;
        this.timeInMillis = timeInMillis;
        this.color = color;
    }

    // Room expects only one constructor by default
    @Ignore
    public Event(int id, int color, @NonNull long timeInMillis, @NonNull String event) {
        this.id = id;
        this.mEvent = event;
        this.timeInMillis = timeInMillis;
        this.color = color;
    }

    public String getEvent(){return this.mEvent;}

    public int getId() { return this.id;};

    public void setId(int id) {
        this.id = id;
    }

    public int getColor() { return this.color; }

    public void setColor(int color) { this.color = color; }

    public long getTimeInMillis() { return this.timeInMillis; }

    public void setTimeInMillis(long timeInMillis) { this.timeInMillis = timeInMillis; };
}